# Change these first
owner: cleyan # Your GitHub organization or username, where this repository lives
repo: status-umas # The name of this repository

sites:
  - name: UMASNet
    url: https://twk.umas.cl/umasnet
  - name: Portal Alumnos
    url: https://portalalumnos.twk.cl
  - name: Portal Docentes
    url: https://portaldocentes.twk.cl
  - name: Portal Titulados
    url: https://portaltitulados.twk.cl
  - name: Matrícula no presencial Alumnos Nuevos
    url: https://twk.umas.cl/mnp
  - name: matrícula No presencial Alumnos antíguos
    url: https://twk.umas.cl/mnpaa
  - name: webService UmasNet
    url: https://twk.umas.cl/wsInterfazUsrTwk/Service1.asmx?WSDL
  - name: Intranet TWK
    url: https://intranet.twk.cl
  - name: Service API TWK
    url: https://service.twk.cl
  - name: CRM xACADEMI
    url: https://crm.xacademi.com/
  - name: AVEA
    url: https://avea.cl/intranet.php?acceso=admin
  - name: Campus xACADEMI
    url: https://campus.xacademi.com/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.twk.cl
  #baseUrl: /status-umas
  logoUrl: https://twk.cl/wp-content/uploads/2021/04/logo-cft-teodoro-wickel-acreditado.svg
  name: Upptime TWK
  introTitle: "Reportes de Estados de Sistemas **TWK**"
  introMessage: Intervalo de verificación: 5 minutos
  navbar:
    - title: Status
      href: /
    - title: TWK.cl
      href: https://twk.cl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
